language: elixir
elixir:
  - 1.8.0
otp_release:
  - 20.0

addons:
  - postgresql: '9.4'

services:
  - postgresql

before_script:
  - mix ecto.create
  - mix ecto.migrate
  - phantomjs --wd &

script:
  - mix test --trace
