version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: elixir:1.9
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: poker_ex_test
          POSTGRES_PASSWORD: $POSTGRES_PASS

    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

  test:
    parallelism: 1
    docker:
      - image: elixir:1.9
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: poker_ex_test
          POSTGRES_PASSWORD: $POSTGRES_PASS

    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix test --trace
      - store_test_results:
          path: _build/test/lib/results

  format:
    parallelism: 1
    docker:
      - image: elixir:1.9
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix format

  lint:
    parallelism: 1
    docker:
      - image: elixir:1.9
    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix credo --only warning

  push_docker_image:
    parallelism: 1
    docker:
      - image: elixir:1.9
    working_directory: ~/app

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./bin/docker_build.sh

workflows:
  version: 2
  build_test_docker_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - format:
          requires:
            - build
      - lint:
          requires:
            - build
      - push_docker_image:
          filters:
            branches:
              only: master
          requires:
            - test
            - format
            - lint